version: "3"

services:
    ###> symfony/mailer ###
    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]

    ###< symfony/mailer ###

    ###> doctrine/doctrine-bundle ###
    database:
        ports:
            - "5432"
    ###< doctrine/doctrine-bundle ###
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_symfony
        restart: always
        depends_on:
            - database
        ports:
            - 8080:80
        environment:
            PMA_HOST: database
